### ISSUE TITLE
No window contents

### ISSUE THREAD

**Issue by snbutler** [dzirbel/kotify#2]
I realise kotify is still under active development and not production ready but I was interested in seeing what kind of functionality it offers. Unfortunately, after successfully acquiring an auth token from spotify, only a blank white window is produced.

The only exception I can see thrown is:

`Exception in thread "DefaultDispatcher-worker-2" Exception in thread "DefaultDispatcher-worker-7" java.lang.IllegalArgumentException: missing current user ID
`

Looking at .kotify/cache/cache.db, I see no entries in the tables 'users'  or 'current_user'. The file .kotify/cache/access_token.json is present and has contents.

**Comment by dzirbel** [comment]
Thanks for the interest! Yep, there was a couple of things broken for brand-new logins without anything yet present in the cache. After the most recent set of commits, I believe these issue should be fixed so you'll be able to play around with it.

As far as what's currently available - not much. The only additional feature on top of Spotify so far is the ability to rate tracks (out of 10 stars). Aside from that, the core functionality of browsing through your library of artists/albums/playlists should largely work, but for the moment expect it to be buggy, slow, and ugly. I am working on Kotify more regularly now, and hoping to have an early usable release (with much more polish and perhaps a couple small features on top of what Spotify's client has) in a month or two, so feel free to check back then :)
